/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ian;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest, "app should be initialized");
    }
}
