/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ian;

public class App {

    public static void main(String[] args) {

        // solve problem here
        Solution solution = new Solution();

        solution.run();

    }

}
