/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ian;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) {
        log.info("running main...");
        // solve problem here
        Solution solution = new Solution();

    }

}
